apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-queue
  # https://www.okteto.com/docs/cloud/ssl
  annotations:
    dev.okteto.com/generate-host: message-queue
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mqueue-service
                port:
                  number: 6379
    # - host: "*megaredhand.cloud.okteto.com"
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: mqueue-service
    #             port:
    #               number: 6379
    # - host: "*fedecolangelo.cloud.okteto.com"
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: mqueue-service
    #             port:
    #               number: 6379
