apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqueue-deployment # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqueue
  template:
    metadata:
      labels:
        app: mqueue
    spec:
      containers:
        - name: mqueue
          image: okteto.dev/message-queue # Sets Image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379 # Exposes container port
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mqueue-service # Sets service name
  labels:
    app: mqueue-service # Labels and Selectors
spec:
  type: NodePort
  selector:
    app: mqueue-deployment
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30007
