name: "Deploy"

on:
  push:
    branches: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy
        uses: okteto/pipeline@latest
        with:
          name: message-queue-megaredhand
          timeout: 15m
